<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>{{ProjectNamespace}}.Infrastructure</RootNamespace>
    <AssemblyName>{{ProjectNamespace}}.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\{{ProjectName}}.Application\{{ProjectName}}.Application.csproj" />
    <ProjectReference Include="..\{{ProjectName}}.Domain\{{ProjectName}}.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="{{EfCoreVersion}}" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="{{NpgsqlEfCoreVersion}}" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="{{ExtensionsVersion}}" />
  </ItemGroup>

</Project>
