<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>{{ProjectNamespace}}.Api.Tests</RootNamespace>
    <AssemblyName>{{ProjectNamespace}}.Api.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Backend\{{ProjectName}}.Api\{{ProjectName}}.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="{{MvcTestingVersion}}" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="{{MicrosoftNetTestSdkVersion}}" />
    <PackageReference Include="xunit" Version="{{XunitVersion}}" />
    <PackageReference Include="xunit.runner.visualstudio" Version="{{XunitRunnerVersion}}">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
